#ifndef __SECT_H__
#define __SECT_H__

#define ALIGN_16(addr) (((addr) + 15) & ~15)

#pragma region KERNEL
// 커널의 메모리 정하기
#define KERNEL_TEXT_START 0x40000000
#define KERNEL_TEXT KERNEL_TEXT_START

#define KERNEL_TEXT_SIZE 0x19000 // 100KB정도 나중에 줄일 예정

#define KERNEL_TEXT_END (KERNEL_TEXT_START + KERNEL_TEXT_SIZE)

// KERNEL_DATA_START

#define MM_ADDR_SIZE 0x5000
#define PM_ADDR_SIZE 0x7000
#define FM_ADDR_SIZE 0x50000
#define DM_ADDR_SIZE 0x5000
#define NM_ADDR_SIZE 0x5000

#define MM_ADDR_START ALIGN_16(KERNEL_TEXT_END)
#define MM_ADDR_END ALIGN_16(MM_ADDR_START + MM_ADDR_SIZE)

#define PM_ADDR_START ALIGN_16(MM_ADDR_END)
#define PM_ADDR_END ALIGN_16(PM_ADDR_START + PM_ADDR_SIZE)

#define FM_ADDR_START ALIGN_16(PM_ADDR_END)
#define FM_ADDR_END ALIGN_16(FM_ADDR_START + FM_ADDR_SIZE)

#define DM_ADDR_START ALIGN_16(FM_ADDR_END)
#define DM_ADDR_END ALIGN_16(DM_ADDR_START + DM_ADDR_SIZE)

#define NM_ADDR_START ALIGN_16(DM_ADDR_END)
#define NM_ADDR_END ALIGN_16(NM_ADDR_START + NM_ADDR_SIZE)

// KERNEl_DATA_END

#define KERNEL_BSS_SIZE 0x10000   // bss 크기
#define KERNEL_STACK_SIZE 0x10000 // 스택 크기 64KB
#define KERNEL_HEAP_SIZE 0x1      // 힙 크기 128KB

#define KERNEL_DATA_END NM_ADDR_END

#define KERNEL_BSS_START KERNEL_DATA_END
#define KERNEL_BSS_END ALIGN_16(KERNEL_BSS_START + KERNEL_BSS_SIZE)

#define KERNEL_STACK_START KERNEL_BSS_END
#define KERNEL_STACK_END ALIGN_16(KERNEL_STACK_START + KERNEL_STACK_SIZE + KERNEL_HEAP_SIZE)

#pragma endregion

#pragma region USER

#define USER_PROC_START KERNEL_STACK_END
#define USER_PROC_END USER_PROC_START + 0x10000000 // 256MB 프로세스 공간

#define USER_FILE_START USER_PROC_END
#define USER_FILE_END USER_FILE_START + 0x88755000 // 2184MB 파일 공간

#pragma endregion

#endif
