#ifndef __KERNEL_SECT_H__
#define __KERNEL_SECT_H__

#define ALIGN_16(addr) (((addr) + 15) & ~15)

#pragma region KERNEL
// 커널의 메모리 정하기
#define KERNEL_TEXT_START 0x40000000
#define KERNEL_TEXT KERNEL_TEXT_START

#define KERNEL_TEXT_SIZE 0x64000 // 커널 텍스트 사이즈 400KB

#define KERNEL_TEXT_END (KERNEL_TEXT_START + KERNEL_TEXT_SIZE)

// 커널 데이터 영역
#define MM_ADDR_SIZE 0x5000
#define PM_ADDR_SIZE 0x7000
#define FM_ADDR_SIZE 0x50000
#define DM_ADDR_SIZE 0x5000
#define NM_ADDR_SIZE 0x5000

#define MM_ADDR_START ALIGN_16(KERNEL_TEXT_END)
#define MM_ADDR_END ALIGN_16(MM_ADDR_START + MM_ADDR_SIZE)

#define PM_ADDR_START ALIGN_16(MM_ADDR_END)
#define PM_ADDR_END ALIGN_16(PM_ADDR_START + PM_ADDR_SIZE)

#define FM_ADDR_START ALIGN_16(PM_ADDR_END)
#define FM_ADDR_END ALIGN_16(FM_ADDR_START + FM_ADDR_SIZE)

#define DM_ADDR_START ALIGN_16(FM_ADDR_END)
#define DM_ADDR_END ALIGN_16(DM_ADDR_START + DM_ADDR_SIZE)

#define NM_ADDR_START ALIGN_16(DM_ADDR_END)
#define NM_ADDR_END ALIGN_16(NM_ADDR_START + NM_ADDR_SIZE)

#define KERNEL_DATA_END NM_ADDR_END

// 커널 BSS & 스택 & 힙 영역
#define KERNEL_BSS_SIZE 0x10000   // BSS 크기 64KB
#define KERNEL_STACK_SIZE 0x10000 // 스택 크기 64KB
#define KERNEL_HEAP_SIZE 0x80000  // 커널 힙 크기 512KB (데몬 200KB 고려)

#define KERNEL_BSS_START KERNEL_DATA_END
#define KERNEL_BSS_END ALIGN_16(KERNEL_BSS_START + KERNEL_BSS_SIZE)

#define KERNEL_STACK_START KERNEL_BSS_END
#define KERNEL_STACK_END ALIGN_16(KERNEL_STACK_START + KERNEL_STACK_SIZE)

#define KERNEL_HEAP_START KERNEL_STACK_END
#define KERNEL_HEAP_END ALIGN_16(KERNEL_HEAP_START + KERNEL_HEAP_SIZE)

#pragma endregion

#pragma region USER

// 유저 프로세스 영역 (유저 힙 & 스택 포함)
#define USER_PROC_START KERNEL_HEAP_END
#define USER_PROC_SIZE 0x10000000 // 유저 프로세스 공간 256MB
#define USER_PROC_END (USER_PROC_START + USER_PROC_SIZE)

// 유저 파일 영역
#define USER_FILE_START USER_PROC_END
#define USER_FILE_SIZE 0x88755000 // 유저 파일 공간 2184MB
#define USER_FILE_END (USER_FILE_START + USER_FILE_SIZE)

#pragma endregion

#endif